spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/employee_directory?serverTimezone=UTC'
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: Enterprise_employees_management_system

logging:
  level:
    org:
      hibernate:
        type: ERROR
        descriptor:
          sql:
            BasicBinder=TRACE: TRACE

jpa:
  hibernate:
    ddl-auto: update
    generate-ddl: true
    show-sql: true


properties:
  hibernate:
    format_sql: true
    generate_statistics: true

management:
  info:
    env:
      enabled: true
      app: null
      name: Enterprise_employees_management_system
      description: A Spring Hibernate exercising app!
      version: 1.0.0

endpoints:
  web:
    exposure: include=*

server:
  error:
    whitelabel.enabled: false

endPoint:
  RestTemplate read from:
    http: //localhost:8080/api/employees;
        //localhost:8080/api/employees;
        //localhost:8080/api/employees/{id};

expose to: //localhost:8080/RestTemplate/getAllEmployee
        //localhost:8080/RestTemplate/addEmployee
        //localhost:8080/RestTemplate/getEmployeeById/4



